<?php

/**
 * @file
 * This file contains all install related hooks for Islandora PlotIt.
 */

/**
 * Implements hook_uninstall().
 */
function islandora_plotit_uninstall() {
  $variables = array(
   'islandora_plotit_label_solr_field',
   'islandora_plotit_long_label_solr_field',
   'islandora_plotit_ascii_name_solr_field',
   'islandora_plotit_group_solr_field',
   'islandora_plotit_sub_group_solr_field',
   'islandora_plotit_event_type_solr_field',
   'islandora_plotit_start_date_solr_field',
   'islandora_plotit_date_type_solr_field',
   'islandora_plotit_location_solr_field',
   'islandora_plotit_lat_long_solr_field',
   'islandora_plotit_location_type_solr_field',
   'islandora_plotit_piont_type_solr_field',
   'islandora_plotit_description_solr_field',
  );
  array_walk($variables, 'variable_del');
}
